apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: root-catalog
spec:
  targets:
  # groups
    - ./groups/whitefield-global-school.yaml
  # components
    - ./components/edutive/assessment-service.yaml
    - ./components/edutive/edutive-frontend.yaml
    - ./components/edutive/email-service.yaml
    - ./components/edutive/student-service.yaml
    - ./components/edutive/teacher-service.yaml
    - ./components/edutive/reportcard-service.yaml

  # apis
    - ./apis/edutive/assessment-api.yaml
    - ./apis/edutive/student-api.yaml
    - /apis/edutive/teacher-api.yaml

  # resources

    - ./resources/kafka.yaml
    - ./resources/mongodb.yaml
    - ./resources/postgres.yaml
    - ./resources/assessment-events.yaml
    - ./resources/student-notification.yaml
  
  # systems

    - ./systems/edutive-school-management.yaml
  
  #users

    - ./users/sairam.yaml
    - ./users/uday.yaml
    
    
   