apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kafka
  description: Kafka Messaging Service
spec:
  type: messaging
  owner: whitefield-global-school
  system: edutive-school-management
  dependsOn:
    - resource:default/student-notifications
    - resource:default/assessment-events