apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: student-service
  description: Student Management Service
  annotations:
    github.com/project-slug: your-org/student-service
    backstage.io/techdocs-ref: "dir:../../docs/edutive"

spec:
  type: service
  lifecycle: production
  owner: whitefield-global-school
  system: edutive-school-management

  dependsOn:
    - resource:default/mongodb

  providesApis:
    - edutive-student-api