apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: teacher-service
  description: Teacher Management Service
  annotations:
    github.com/project-slug: your-org/teacher-service
spec:
  type: service
  lifecycle: production
  owner: whitefield-global-school
  system: edutive-school-management

  dependsOn:
    - resource:default/mongodb